// GENERATED by export/make_baseline.py — DO NOT EDIT.
// Benign (nevus) baseline of the 18 handcraft features, used to express each
// lesion's ABCDE values as a deviation from the typical benign mole.
class FeatureBaseline {
  static const List<String> names = [
    "A4", "B", "D", "Lab_a_kurt", "Lab_b_std", "Lab_a_std", "Lab_b_skew", "internal_R1", "internal_R2", "internal_R4", "internal_R8", "internal_R16", "external_R1", "external_R2", "external_R4", "external_R8", "external_R16", "fractal_D"
  ];

  /// Mean of each feature over the benign (nevus) population.
  static const List<double> mean = [0.488351, 1.634040, 601.896514, -0.351838, 5.901301, 4.744226, -0.179221, 1973.856979, 3968.359612, 7725.040983, 14856.790430, 28491.483324, 1978.105243, 3984.758758, 7751.957491, 14889.772571, 28760.508204, 1.028633];

  /// Population std of each feature over benign lesions.
  static const List<double> std = [0.403037, 0.479607, 643.997774, 1.114110, 1.872839, 1.508235, 0.513672, 2415.352146, 4812.749425, 9482.422018, 18445.814229, 35161.367395, 2414.870867, 4809.471942, 9458.420980, 18323.963832, 34420.448057, 0.035199];

  /// +1 if a higher value is more concerning (melanoma side), -1 otherwise.
  // NB: A4 (index 0) corrected to -1 — higher A4 = more symmetric = less concerning.
  static const List<double> sign = [-1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 1.000000];

  /// Oriented z-score: >0 means "more atypical than a benign mole".
  static double orientedZ(int i, double value) =>
      sign[i] * (value - mean[i]) / std[i];
}
