"""
Generate the benign (nevus) baseline of the 18 handcraft features for the
on-device ABCDE readout. For each feature we emit:
  mean, std  -> over the NEVUS (benign) population
  sign       -> +1 if a HIGHER value is more concerning (melanoma side),
                -1 otherwise (so an oriented z-score >0 always means "atypical")

Writes Mobile_App/lib/ml/feature_baseline.dart

Run:  C:\\v\\Scripts\\python.exe export\\make_baseline.py
"""
from pathlib import Path

import pandas as pd
from derm import paths

OUT = paths.APP / "lib" / "ml" / "feature_baseline.dart"

df = pd.read_csv(paths.FEATURES_CSV)
cols = list(df.columns[:-1])  # 18 features
assert len(cols) == 18, f"expected 18 features, got {len(cols)}"

nevus = df[df["Class"] == 0]
mel = df[df["Class"] == 1]

mean = nevus[cols].mean()
std = nevus[cols].std(ddof=0).replace(0, 1e-6)
# direction of concern: does melanoma sit above or below the benign mean?
sign = ((mel[cols].mean() - mean) >= 0).map(lambda b: 1.0 if b else -1.0)


def fmt(series):
    return ", ".join(f"{series[c]:.6f}" for c in cols)


dart = f'''// GENERATED by export/make_baseline.py — DO NOT EDIT.
// Benign (nevus) baseline of the 18 handcraft features, used to express each
// lesion's ABCDE values as a deviation from the typical benign mole.
class FeatureBaseline {{
  static const List<String> names = [
    {", ".join(f'"{c}"' for c in cols)}
  ];

  /// Mean of each feature over the benign (nevus) population.
  static const List<double> mean = [{fmt(mean)}];

  /// Population std of each feature over benign lesions.
  static const List<double> std = [{fmt(std)}];

  /// +1 if a higher value is more concerning (melanoma side), -1 otherwise.
  static const List<double> sign = [{fmt(sign)}];

  /// Oriented z-score: >0 means "more atypical than a benign mole".
  static double orientedZ(int i, double value) =>
      sign[i] * (value - mean[i]) / std[i];
}}
'''

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(dart, encoding="utf-8")
print(f"wrote {OUT}")
print("nevus n=", len(nevus), " melanoma n=", len(mel))
for c in cols:
    print(f"  {c:<14} nevus_mean={mean[c]:.4f}  sign={'+' if sign[c]>0 else '-'}")
